### ISSUE TITLE
Hunchentoot handler bug (or logger?)

### ISSUE THREAD

**Issue by gibsonf1** [fukamachi/clack#97] opened 2015-02-08 16:49 UTC
When running with hunchentoot, if this url is passed: http://localhost/~wsdocs/images/important.gif - the tilde seems to be getting intrepreted as a format directive.

From the log:
[2015-02-08 07:08:40 [WARNING]] Warning while processing connection: Too few arguments (0) to FORMAT "10.220.159.95 - [08/Feb/2015:07:08:40 -06:00] \"GET /~wsdocs/images/important.gif HTTP/1.0\" 404 940 \"-\" \"-\"": requires at least 1.
See also:
  The ANSI Standard, Section 22.3.10.2
; 
; caught WARNING:
;   Too few arguments (0) to FORMAT "10.220.159.95 - [08/Feb/2015:07:08:40 -06:00] \"GET /~wsdocs/images/important.gif HTTP/1.0\" 404 940 \"-\" \"-\"": requires at least 1.
;   See also:
;     The ANSI Standard, Section 22.3.10.2
; 
; compilation unit finished
;   caught 1 WARNING condition

debugger invoked on a SB-FORMAT:FORMAT-ERROR in thread
#<THREAD "hunchentoot-worker-10.220.159.95:56112" RUNNING {100EC1FED3}>:
  error in FORMAT: required argument missing
  10.220.159.95 - [08/Feb/2015:07:08:40 -06:00] "GET /~wsdocs/images/important.gif HTTP/1.0" 404 940 "-" "-"
                                                       ^
[2015-02-08 07:14:11 [WARNING]] Can't handle a new request, too many request threads already

**Comment by gibsonf1** [comment] 2015-02-08 16:57
It is definitely in the logger as when I turned that middleware off the problem went away.

**Comment by fukamachi** [comment] 2015-02-09 04:02
I couldn't reproduce it with this code.

```common-lisp
(clack:clackup
  (clack:wrap (make-instance 'clack.middleware.accesslog:<clack-middleware-accesslog>)
              (lambda (env) '(200 () ("Hi")))))
;; and open "http://localhost:5000/~wsdocs/images/important.gif" from Safari.
```

Are you using the latest Clack?

**Comment by gibsonf1** [comment] 2015-02-09 19:38
Instead of using the standard quicklisp downloads, I cloned caveman, clack and quri from github and now it works perfectly - thanks!

**Comment by fukamachi** [comment] 2015-02-10 00:53
As Clack.Middleware.Accesslog hasn't been modified these days, your local Quicklisp dist might be quite old.

You can check the version like this:

```common-lisp
(ql-dist:dist "quicklisp")
#<QL-DIST:DIST quicklisp 2015-01-13>
```

You can update your dist by `(ql:update-all-dists)`.

**Comment by fukamachi** [comment] 2015-02-10 00:53
Anyway, I'm closing this.
Feel free to reopen this if you still have the problem.

**Closed by fukamachi** 2015-02-10 00:53 UTC

**Comment by gibsonf1** [comment] 2015-02-12 16:31
My quicklisp dist is up to date - it looks like the error might have been caused by changes in quri.
