### ISSUE TITLE
clack-v1-compat has some compilation errors

### ISSUE THREAD

**Issue by eudoxia0** [fukamachi/clack#119] opened 2015-07-06 22:13 UTC
Long story short, I've built a clone of node-webkit/Electron and it works great. The only problem is that when deploying an app, you have to compile your web application to native. And since all three Clack web frameworks use clack-v1-compat, you can't actually do this, since it fails at compile time.

You can verify this with `(asdf:compile-system :clack-v1-compat :force t)`. Most of the errors seem like some package definition/redefinition problems.

**Comment by Rudolph-Miller** [comment] 2015-07-06 22:56
It sounds a great job!

I think the issue is produced by compile-system (os load-system) twice, but not by just compile-system (or load-system) once,
due to combinations of `(:export :symbol)` in `defpackage` and `(export 'other-symbol)` with SBCL.

You can make this silent with wrapping your compile-system, with
```Lisp
(handler-bind ((warning (lambda (c)
                          (declare (ignore c))
                          (muffle-warning))))
  ...)
```
.

**Comment by eudoxia0** [comment] 2015-07-06 23:17
At least here, compiling `clack-v1-compat` just one triggers the error (although this could be because of older fasl files in my cache).

I tried wrapping the call to `asdf:compile-system` around that warning-muffling code, but it still errors with:

```lisp
The symbol "FINALIZE" is not external in the CLACK.RESPONSE package.
```

**Comment by Rudolph-Miller** [comment] 2015-07-07 01:34
Okay, I could reproduce the error, and could avoid it by
```Lisp
(handler-bind ((warning (lambda (c)
                          (declare (ignore c))
                          (muffle-warning))))
  (asdf:load-system :clack-v1-compat :force t)
  (asdf:compile-system :clack-v1-compat :force t))
```
.

**Comment by fukamachi** [comment] 2015-07-07 02:12
I made some changes at "fix-clack-v1-compat" branch, that unexports all symbols in clack.response and clack.request when those packages exist.

**Comment by fukamachi** [comment] 2015-07-07 15:48
Merged. I believe clack-v1-compat can be compiled now.
There're still some compilation errors about redefinition of `defpackage`s when `:force t` is specified, however, I don't think it's serious as it's pretty rare use case and can be avoided with `handler-bind` @Rudolph-Miller is saying above.

**Closed by fukamachi** 2015-07-07 15:48 UTC

**Comment by eudoxia0** [comment] 2015-07-08 02:14
Thanks guys, works perfectly now.
